Feat : 크루 조회
Likelion12/Backend_Team pull request #55
Opened 2024-08-02 17:46 UTC by hd0rable

## 요약 (Summary)
- [x] 크루 조회를 위한 api를 작성했습니다 [크루 조회 api 명세서](https://www.notion.so/likeklionatkonkuk/5f61e380ce384a22a7edc7c57c439fe5)
- [x] 피그마에 나와있는 값들을 반환합니다.
- [x] 페이징 처리를 추가했습니다

## 🔑 변경 사항 (Key Changes)

- `GetCrewInquiryResponse dto  작성` : 크루 조회를 위한 dto를 작성했습니다.
- `CrewService.getCrewInquiries 작성` : 크루 조회를 위한 서비스를 작성했습니다. 해당하는 크루를 페이징처리를 통해 리스트로 반환하도록 했습니다.
- `CrewController.getCrewInquiries 작성` : 크루 조회를 위한 컨트롤러를 작성했습니다. 조회에 대한 다이렉트는 /inquiry로 작성했습니다.
- `SearchRequest 작성` : 페이징처리를 위한 dto를 작성했습니다.

## 📝 리뷰 요구사항 (To Reviewers)

- [x] 명세서대로 제대로 반환되는지
- [ ] 페이징 처리가 제대로 되는지

## 확인 방법 

코드를 실행시키고,mysql workbench에서 다음 쿼리문을 실행시켜주세요.
member 중 하나는 리뷰자의 정보로 수정해야합니다.

```
use likelion12;

INSERT INTO exercise (created_at, modified_at,exercise_name, status) VALUES
('2024-06-30 12:00:00.000000', '2024-06-30 12:30:00.000000', '축구', 'ACTIVE');
INSERT INTO exercise (created_at, modified_at,exercise_name, status) VALUES
('2024-06-30 12:00:00.000000', '2024-06-30 12:30:00.000000', '농구', 'ACTIVE');

INSERT INTO member (created_at, modified_at, email, member_img, member_name, gender,exercise_id,status) VALUES
('2024-06-30 12:00:00.000000', '2024-06-30 12:30:00.000000', 'sungginmama@naver.com', '프로필 이미지', '강희진', 'F', 1,'ACTIVE'); -- 리뷰자 계정
INSERT INTO member (created_at, modified_at, email, member_img, member_name, gender,exercise_id,status) VALUES
('2024-07-30 12:00:00.000000', '2024-07-30 12:30:00.000000', 'kanghuijin12@gmail.com', '프로필 이미지', '강의진', 'F', 1,'ACTIVE');
INSERT INTO member (created_at, modified_at, email, member_img, member_name, gender,exercise_id,status) VALUES
('2024-07-30 12:00:00.000000', '2024-07-30 12:30:00.000000', 'kanghuijin12３@gmail.com', '프로필 이미지', '강', 'F', 2,'ACTIVE');

INSERT INTO activity_region (created_at, modified_at, activity_region_name,status) VALUES
('2024-06-30 12:00:00.000000', '2024-06-30 12:30:00.000000', '광진구','ACTIVE');
INSERT INTO facility (created_at, modified_at, facility_name, facility_city,facility_dong,facility_gu, facility_phone, status) VALUES
('2024-06-30 12:00:00.000000', '2024-06-30 12:30:00.000000', '광진구 체육관', '서울시','화양동','광진구' ,'000-0000','ACTIVE');
INSERT INTO facility (created_at, modified_at, facility_name, facility_city,facility_dong,facility_gu, facility_phone, status) VALUES
('2024-06-30 12:00:00.000000', '2024-06-30 12:30:00.000000', '광진구 체육관2', '서울시2','화양동2','광진구2' ,'000-00002','ACTIVE');

INSERT INTO crew (crew_cost, total_recruits, activity_region_id, created_at, exercise_id, facility_id, modified_at, comment, comment_simple, crew_img, crew_name, gender, level, status) VALUES
(1500, 50, 1, '2024-08-01 09:00:00', 1, 2, '2024-08-01 09:00:00', '크루1입니다~', '크루1', '크루1.png', '크루1', 'M', 'A', 'ACTIVE');
INSERT INTO crew (crew_cost, total_recruits, activity_region_id, created_at, exercise_id, facility_id, modified_at, comment, comment_simple, crew_img, crew_name, gender, level, status) VALUES
(1200, 40, 1, '2024-08-02 10:00:00', 1, 2, '2024-08-02 10:00:00', '크루2입니다~', '크루2', '크루2.png', '크루2', 'F', 'S', 'ACTIVE');
INSERT INTO crew (crew_cost, total_recruits, activity_region_id, created_at, exercise_id, facility_id, modified_at, comment, comment_simple, crew_img, crew_name, gender, level, status) VALUES
(1200, 40, 1, '2024-08-02 10:00:00', 2, 1, '2024-08-02 10:00:00', '크루3입니다~', '크루3', '크루3.png', '크루3', 'F', 'S', 'ACTIVE');
INSERT INTO crew (crew_cost, total_recruits, activity_region_id, created_at, exercise_id, facility_id, modified_at, comment, comment_simple, crew_img, crew_name, gender, level, status) VALUES
(1200, 40, 1, '2024-08-02 10:00:00', 2, 1, '2024-08-02 10:00:00', '크루4입니다~', '크루4', '크루4.png', '크루4', 'F', 'S', 'ACTIVE');
INSERT INTO crew (crew_cost, total_recruits, activity_region_id, created_at, exercise_id, facility_id, modified_at, comment, comment_simple, crew_img, crew_name, gender, level, status) VALUES
(1200, 40, 1, '2024-08-02 10:00:00', 2, 1, '2024-08-02 10:00:00', '크루5입니다~', '크루5', '크루5.png', '크루5', 'F', 'S', 'ACTIVE');
INSERT INTO crew (crew_cost, total_recruits, activity_region_id, created_at, exercise_id, facility_id, modified_at, comment, comment_simple, crew_img, crew_name, gender, level, status) VALUES
(1200, 40, 1, '2024-08-02 10:00:00', 2, 1, '2024-08-02 10:00:00', '크루6입니다~', '크루6', '크루6.png', '크루6', 'F', 'S', 'ACTIVE');

```

그 다음 카카오 소셜 로그인을 해주세요.

`https://kauth.kakao.com/oauth/authorize?client_id=220ac935aaf5aa43884ee21823d82237&redirect_uri=http://localhost:8080/auth/kakao/callback&response_type=code`

엑세스토큰을 postman에 넣고 테스트 해주세요

다음 주소로 GET 요청 보내주세요

`http://localhost:8080/crew/inquiry`

리퀘스트 body는 다음과 같습니다.
```
{
	"page" : 1,
	"recordSize" : 2,
	"pageSize" : 5
}
```
```
{
	"page" : 2,
	"recordSize" : 3,
	"pageSize" : 5
}
```

![image](https://github.com/user-attachments/assets/5c2cb370-0db9-4fe3-83c0-ee3af2cad3ec)

![image](https://github.com/user-attachments/assets/784eb73f-1bf1-4299-9f3c-a945a74c6327)

위와같이 페이징 처리가 제대로 되어 해당하는 크루리스트가 반환되면 성공입니다!

2024-08-03 14:44 UTC, jsilver01 requested changes
<img width="412" alt="스크린샷 2024-08-03 오후 11 43 51" src="https://github.com/user-attachments/assets/ab6e95ca-89c1-4ab6-b4bb-8aca04b40462">
혹시 이 화면에 대한 api 구현한게 맞으실까요??? 요 부분은 id 값은 필요하지 않을 것 같습니다! 그냥 전체적으로 보여주면 되는 화면이라서요! 대신에 페이징처리가 좀 필요할 것 같습니다! 확인부탁드립니다~

2024-08-04 09:11 UTC, hd0rable commented
수정요청사항대로 수정했습니다!

2024-08-05 10:04 UTC, jsilver01 requested changes
일단 페이징 처리 해주신거 너무 좋습니다! 충돌 난 부분은 제가 수정해서 다시 코드 돌려보고 문제없이 돌아가는 것 확인했어요! 포스트맨으로도 응답 날라오는 것 전부 확인했습니다!! 수고하셨어요!! 
그런데 지금 recordSize 로 응답보내주는 갯수가 달라지는 것 맞나요??? 맞다면 이건 요청으로 받지 않고 저희가 피그마만큼의 갯수를 반환해줘야할 것 같습니다! 그리고 pageSize 이것은 무엇인지 궁금합니다!

2024-08-05 10:14 UTC, hd0rable commented
아 기본화면에는 9개인데 혹시 다른 페이지에서도 페이징처리가 필요할때 저 dto를 그대로쓰려고 받아서 사용하도록 했습니당 
다른모든화면에서 무조건 9개로 반환하니까 9개로 고정해놓으면 될까요??
<img width="227" alt="image" src="https://github.com/user-attachments/assets/df1c06a3-f00c-47c6-ab9a-d8c9bc9062e3">
pageSize 사이즈는 하단화면에 해당하는 사이즈입니다!! 
페이지네이션 처리할때 쓰려고작성한건데.. 지금은 필요없는거 같아서 삭제해도될 것 같습니다~

2024-08-05 10:29 UTC, jsilver01 commented
> 아 기본화면에는 9개인데 혹시 다른 페이지에서도 페이징처리가 필요할때 저 dto를 그대로쓰려고 받아서 사용하도록 했습니당 다른모든화면에서 무조건 9개로 반환하니까 9개로 고정해놓으면 될까요?? <img alt="image" width="227" src="https://private-user-images.githubusercontent.com/131003143/355063697-df1c06a3-f00c-47c6-ab9a-d8c9bc9062e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTM5OTEsIm5iZiI6MTcyMjg1MzY5MSwicGF0aCI6Ii8xMzEwMDMxNDMvMzU1MDYzNjk3LWRmMWMwNmEzLWYwMGMtNDdjNi1hYjlhLWQ4YzliYzkwNjJlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxMDI4MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYWI5ZmE3ZWM4ODIwZWY5NmI3ZTk0YWIwNGM2MzRiZTY1YTg0NGY3NTYyZjU4NTY0ZDMyODQ1ZDk1MjVmM2U5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SSFBkKfXXzupDrQtqnFIUVXDwPILShAPFJQ3x8By_OI"> pageSize 사이즈는 하단화면에 해당하는 사이즈입니다!! 페이지네이션 처리할때 쓰려고작성한건데.. 지금은 필요없는거 같아서 삭제해도될 것 같습니다~

넵!! 알겠습니다! 갯수는 9개로 고정하면 될 것 같습니다~!!

2024-08-05 10:58 UTC, hd0rable commented
수정완료했습니다~

2024-08-05 16:22 UTC, jsilver01 approved these changes
충돌 해결했고 포스트맨으로 정상작동 확인했습니다~ 머지할게요!

2024-08-05 16:22 UTC, merged